### ISSUE TITLE
白黒校正の返り値を `[(Float, Float)]` にしてもいいかも。

### ISSUE THREAD

**Issue by mutokeigo** [mutokeigo/ReagentCamera#33]
返り値を `[(Float, Float)]` にしてこの時点でwhite/blackあってもいいかも。
KKEさんも仕様が分かっていない段階なので、今の時点でかえる必要は特別はないでしょう。

_Originally posted by @ryotapoi in https://github.com/_render_node/MDExOlB1bGxSZXF1ZXN0MzQ1NTYwMTY3/pull_requests/unread_timeline_

**Comment by mutokeigo** [comment]
今の仕様、このissueはやらなくて良いかなと思うのでCloseします。

**Comment by ryotapoi** [comment]
Milestoneに適当なの作ってぶち込んでおいてもいい気がするけど、Closeで問題ないでしょう。
これ以上修正することあるかもわからないし。
